spring:
  jdbc:
    datasource:
      driver-class-name: org.postgresql.Driver
      password: tiger
      url: jdbc:postgresql://localhost:5432/ish
      username: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
   
